### ISSUE TITLE
Question about the previous belief state

### ISSUE THREAD

**Issue by ha-lins** [renll/ComerNet#2]
Hi @renll ,

Thanks for the released code! I have a question about the details of the previous belief state. During training, is the previous belief state exactly **the ground truth** or **predicted ones** previously? Could you pls point it out in the code?

Thanks a lot!

**Comment by renll** [comment]
During training, the previous belief state is exactly the ground truth. https://github.com/renll/ComerNet/blob/92d0a3dc819590d5ae15f806b67befded99a281a/models/seq2seq.py#L54
